version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  pre_build:
    commands:
      - echo "No pre-build steps required"
  build:
    commands:
      - echo "No build steps required for plain HTML"
  post_build:
    commands:
      - echo "Build process completed successfully"

artifacts:
  files:
    - '**/*.html'
    - '**/*.css'
    - '**/*.js'
    - '**/*.png'
    - '**/*.jpg'
    - '**/*.svg'
    - '**/*.ico'
